on:
  pull_request_target:
   branches:
     - main
  push:
jobs:
  PoC:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          
      - name: legit check
        run: echo "Normal things"
        shell: bash

      - name: Execute_code
        run: python3 main.py
